apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-secret
  namespace: support-me
spec:
  provider: gke
  secretObjects:
    - secretName: auth-db-credentials
      type: Opaque
      data:
        - objectName: db-password
          key: password
    - secretName: auth-admin-credentials
      type: Opaque
      data:
        - objectName: admin-password
          key: password
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_NUMBER}/secrets/support-me-prod-auth-db-password/versions/latest"
        fileName: "db-password"
      - resourceName: "projects/${GCP_PROJECT_NUMBER}/secrets/support-me-prod-keycloak-admin-password/versions/latest"
        fileName: "admin-password"
